import json
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse, PlainTextResponse, Response
from backend.db.database import get_db

router = APIRouter(prefix="/api/report", tags=["report"])


async def _get_analysis_data(analysis_id: int, db) -> dict | None:
    cursor = await db.execute("SELECT * FROM analyses WHERE id = ?", (analysis_id,))
    analysis = await cursor.fetchone()
    if not analysis:
        return None

    cursor = await db.execute(
        "SELECT * FROM pipeline_stages WHERE analysis_id = ? ORDER BY stage_number",
        (analysis_id,),
    )
    stages = await cursor.fetchall()

    cursor = await db.execute(
        "SELECT * FROM files WHERE id = ?",
        (analysis["file_id"],),
    )
    file_row = await cursor.fetchone()

    return {
        "analysis": dict(analysis),
        "stages": [dict(s) for s in stages],
        "file": dict(file_row) if file_row else None,
    }


_PDF_REPLACEMENTS = {
    "—": "-", "–": "-", "•": "*", "’": "'", "‘": "'",
    "“": '"', "”": '"', "…": "...", "→": "->",
    "✅": "[done]", "⏳": "[running]", "⬜": "[pending]",
}


def _pdf_safe(text: str) -> str:
    """Core PDF fonts (Courier) only encode latin-1. Map common unicode to
    ASCII, then drop anything still unrepresentable, so PDF export never throws
    (an unhandled char previously aborted the whole PDF -> empty download)."""
    for uni, ascii_ in _PDF_REPLACEMENTS.items():
        text = text.replace(uni, ascii_)
    return text.encode("latin-1", "replace").decode("latin-1")


def _build_markdown(data: dict) -> str:
    a = data.get("analysis", {})
    lines = []
    lines.append(f"# RCA Report - Analysis #{a.get('id', 'N/A')}")
    lines.append("")
    lines.append(f"**File:** {(data.get('file') or {}).get('name', 'N/A')}")
    lines.append(f"**Root Cause:** {a.get('root_cause', 'Unknown')}")
    lines.append(f"**Severity:** {a.get('severity', 'Info')}")
    lines.append(f"**CVSS Score:** {a.get('cvss_score', 'N/A')}")
    lines.append(f"**CVSS Vector:** {a.get('cvss_vector', 'N/A')}")
    lines.append(f"**CVE ID:** {a.get('cve_id', 'None')}")
    lines.append(f"**Confidence:** {a.get('confidence', 'N/A')}")
    lines.append(f"**Summary:** {a.get('summary', 'N/A')}")
    lines.append("")
    lines.append("## Pipeline Stages")
    lines.append("")
    for s in data.get("stages", []):
        status_icon = "✅" if s.get("status") == "complete" else "⏳" if s.get("status") == "running" else "⬜"
        lines.append(f"- {status_icon} **Stage {s['stage_number']}: {s['stage_name']}** — {s.get('status', 'pending')}")
        if s.get("explanation"):
            lines.append(f"  - *{s['explanation']}*")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by RCAi - {data.get('generated_at', 'N/A')}*")
    return "\n".join(lines)


@router.get("/{analysis_id}/markdown")
async def export_markdown(analysis_id: int):
    db = await get_db()
    data = await _get_analysis_data(analysis_id, db)
    await db.close()
    if not data:
        raise HTTPException(status_code=404, detail="Analysis not found")
    data["generated_at"] = datetime.now(timezone.utc).isoformat()
    md = _build_markdown(data)
    return PlainTextResponse(
        content=md,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename=rcai-report-{analysis_id}.md"},
    )


def _render_pdf(md: str) -> bytes:
    """Render the markdown report to PDF bytes. Uses full-width multi_cell for
    every line (the core Courier font wraps long unbroken tokens like CVSS
    vectors) and indents list items with spaces rather than an offset cell, so
    fpdf never hits a 'not enough horizontal space' state."""
    from fpdf import FPDF
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Courier", "", 10)
    epw = pdf.epw  # effective page width

    for line in md.split("\n"):
        line = _pdf_safe(line.rstrip())
        if line.startswith("# "):
            pdf.set_font("Courier", "B", 14)
            pdf.multi_cell(epw, 8, line[2:])
            pdf.set_font("Courier", "", 10)
            pdf.ln(2)
        elif line.startswith("## "):
            pdf.set_font("Courier", "B", 12)
            pdf.multi_cell(epw, 7, line[3:])
            pdf.set_font("Courier", "", 10)
            pdf.ln(1)
        elif line.startswith("- ") or line.startswith("* "):
            raw = line[2:].replace("**", "").replace("*", "")
            pdf.multi_cell(epw, 5, "  * " + raw)
        elif "**" in line:
            pdf.multi_cell(epw, 5, line.replace("**", "").replace("*", ""))
        elif line == "---":
            pdf.multi_cell(epw, 5, "-" * 60)
        elif line:
            pdf.multi_cell(epw, 5, line)
        else:
            pdf.ln(2)

    return bytes(pdf.output())


@router.get("/{analysis_id}/pdf")
async def export_pdf(analysis_id: int):
    db = await get_db()
    data = await _get_analysis_data(analysis_id, db)
    await db.close()
    if not data:
        raise HTTPException(status_code=404, detail="Analysis not found")
    data["generated_at"] = datetime.now(timezone.utc).isoformat()

    md = _build_markdown(data)

    try:
        pdf_bytes = _render_pdf(md)
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=rcai-report-{analysis_id}.pdf"},
        )
    except ImportError:
        return PlainTextResponse(
            content="PDF generation requires fpdf2. Install with: pip install fpdf2\n\n" + md,
            media_type="text/plain",
        )
    except Exception:
        return PlainTextResponse(
            content="PDF generation failed. Check server logs for details.\n\n" + md,
            media_type="text/plain",
        )


@router.get("/{analysis_id}")
async def generate_report(analysis_id: int):
    db = await get_db()
    cursor = await db.execute("SELECT * FROM analyses WHERE id = ?", (analysis_id,))
    analysis = await cursor.fetchone()
    if not analysis:
        await db.close()
        raise HTTPException(status_code=404, detail="Analysis not found")

    cursor = await db.execute(
        "SELECT * FROM pipeline_stages WHERE analysis_id = ? ORDER BY stage_number",
        (analysis_id,),
    )
    stages = await cursor.fetchall()
    await db.close()

    report = {
        "analysis": dict(analysis),
        "stages": [dict(s) for s in stages],
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    return JSONResponse(content=report, headers={
        "Content-Disposition": f"attachment; filename=rcai-report-{analysis_id}.json"
    })
